### ISSUE TITLE
Read Only Mode not Rendering.

### ISSUE THREAD

**Issue by RachanaBP** [hunterkoppenclevr/mention-input-widget#3]
Hi, 
I am trying the view the Message added in the widget. However, I cannot see the widget in Read only Mode. 
![image](https://user-images.githubusercontent.com/42468929/200795157-2c7b4686-10de-4db6-97b9-c0ccd0c1b36d.png)
The Screen looks like below. I donot see any Read only class added into it as seen in the demo Project. Am i missing something here ?
![image](https://user-images.githubusercontent.com/42468929/200795442-97934e84-c1ba-40f3-8415-e133a6b707f8.png)

**Comment by hunter-koppen** [comment]
Hi Rachana, Ill have a look at it tomorrow! Thanks for reporting it.

**Comment by JarnoKoopman** [comment]
Hi Hunter,

Same issue here. the read only seems the be missing the attributes that are showing in your demo project. Also, for some reason it never renders a multi line in edit mode, even tho its selected.  Hopefully you can solve it because its a very nice widget!

![image](https://user-images.githubusercontent.com/70951660/201117471-6b305152-3674-4dbd-a19f-a8701c207b48.png)

**Comment by hunter-koppen** [comment]
@JarnoKoopman @RachanaBP Hi guys, I've published a new version of the widget which should solve the read-only option.
Also Jarno I could not reproduce the multiline issue. Maybe it only seems like its not multiline? If you press enter while in the textbox does it grow or does it stay one-line? Because thats basically what multiline means.

**Comment by JarnoKoopman** [comment]
@hunterkoppenclevr it works indeed now when i use it in a list view. However, i wanted to make a switch to the gallery because of performance but there i see it behaves the same way , an empty text box that is not read only.

Any idea why it works when used in a list view but not in the gallery?

**Comment by hunter-koppen** [comment]
@JarnoKoopman What is your specific setup? I have tested it in a gallery widget and it seems to work fine for me. 
![image](https://user-images.githubusercontent.com/75416593/201354239-c9c7f7cb-c922-4628-a129-7e5e42e3e928.png)

**Comment by RachanaBP** [comment]
Thanks Hunterkooper for a quick support.
Will check and revert back

sent from Android phone

**Comment by RachanaBP** [comment]
fix is working great... Thanks.. Just a query.. is there a way where i can prepopulate a mention ?? the scenario is like below.. 
we have a comment and user replies on a comment, in that case we need to tag the original user while replying.
